//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMApp.HCMSdk {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AttributeCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class AttributeCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FormattedValueCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringstring")]
    [System.SerializableAttribute()]
    public class FormattedValueCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, string>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RelatedEntityCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfRelationshipEntityCollectionX_PsK4FkN")]
    [System.SerializableAttribute()]
    public class RelatedEntityCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Relationship, Microsoft.Xrm.Sdk.EntityCollection>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LocalizedLabelCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="LocalizedLabel")]
    [System.SerializableAttribute()]
    public class LocalizedLabelCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.LocalizedLabel> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EntityReferenceCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="EntityReference")]
    [System.SerializableAttribute()]
    public class EntityReferenceCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.EntityReference> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AttributePrivilegeCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="AttributePrivilege")]
    [System.SerializableAttribute()]
    public class AttributePrivilegeCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.AttributePrivilege> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RelationshipQueryCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfRelationshipQueryBaseX_PsK4FkN")]
    [System.SerializableAttribute()]
    public class RelationshipQueryCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Relationship, Microsoft.Xrm.Sdk.Query.QueryBase>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EntityMetadataCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="EntityMetadata")]
    [System.SerializableAttribute()]
    public class EntityMetadataCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.Metadata.EntityMetadata> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ParameterCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class ParameterCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ErrorDetailCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class ErrorDetailCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="QuickFindResultCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="QuickFindResult")]
    [System.SerializableAttribute()]
    public class QuickFindResultCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.QuickFindResult> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AttributeMappingCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="AttributeMapping")]
    [System.SerializableAttribute()]
    public class AttributeMappingCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.AttributeMapping> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DeletedMetadataCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Metadata/Query", ItemName="KeyValuePairOfDeletedMetadataFiltersArrayOfguidPlUv_PKtF")]
    [System.SerializableAttribute()]
    public class DeletedMetadataCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Metadata.Query.DeletedMetadataFilters, System.Guid[]>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EndpointCollection", Namespace="http://schemas.microsoft.com/xrm/2014/Contracts", ItemName="KeyValuePairOfEndpointTypestringyDL0RVHi")]
    [System.SerializableAttribute()]
    public class EndpointCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Organization.EndpointType, string>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OrganizationRequestCollection", Namespace="http://schemas.microsoft.com/xrm/2012/Contracts", ItemName="OrganizationRequest")]
    [System.SerializableAttribute()]
    public class OrganizationRequestCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.OrganizationRequest> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OrganizationResponseCollection", Namespace="http://schemas.microsoft.com/xrm/2012/Contracts", ItemName="ExecuteMultipleResponseItem")]
    [System.SerializableAttribute()]
    public class OrganizationResponseCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.ExecuteMultipleResponseItem> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AuditPartitionDetailCollection", Namespace="http://schemas.microsoft.com/crm/2011/Contracts", ItemName="AuditPartitionDetail")]
    [System.SerializableAttribute()]
    public class AuditPartitionDetailCollection : System.Collections.Generic.List<Microsoft.Crm.Sdk.Messages.AuditPartitionDetail> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="QueryByEntityNameDictionary", Namespace="http://schemas.microsoft.com/crm/2011/Contracts", ItemName="KeyValuePairOfstringQueryBasegUGIFE1S")]
    [System.SerializableAttribute()]
    public class QueryByEntityNameDictionary : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, Microsoft.Xrm.Sdk.Query.QueryBase>> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Services", ConfigurationName="HCMSdk.IOrganizationService")]
    public interface IOrganizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        System.Guid Create(Microsoft.Xrm.Sdk.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ateResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateAsync(Microsoft.Xrm.Sdk.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieve", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        Microsoft.Xrm.Sdk.Entity Retrieve(string entityName, System.Guid id, Microsoft.Xrm.Sdk.Query.ColumnSet columnSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieve", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveResponse")]
        System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.Entity> RetrieveAsync(string entityName, System.Guid id, Microsoft.Xrm.Sdk.Query.ColumnSet columnSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Update(Microsoft.Xrm.Sdk.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Microsoft.Xrm.Sdk.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "ete", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "eteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "eteOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Delete(string entityName, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "ete", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "eteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string entityName, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cute", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cuteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cuteOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        Microsoft.Xrm.Sdk.OrganizationResponse Execute(Microsoft.Xrm.Sdk.OrganizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cute", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cuteResponse")]
        System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.OrganizationResponse> ExecuteAsync(Microsoft.Xrm.Sdk.OrganizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Associate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, HCMApp.HCMSdk.EntityReferenceCollection relatedEntities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociateResponse")]
        System.Threading.Tasks.Task AssociateAsync(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, HCMApp.HCMSdk.EntityReferenceCollection relatedEntities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Disassociate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, HCMApp.HCMSdk.EntityReferenceCollection relatedEntities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associateResponse")]
        System.Threading.Tasks.Task DisassociateAsync(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, HCMApp.HCMSdk.EntityReferenceCollection relatedEntities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultiple", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultipleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultipleOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Xrm.Sdk.Query.QueryByAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Xrm.Sdk.Query.FetchExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Xrm.Sdk.Query.QueryExpression))]
        Microsoft.Xrm.Sdk.EntityCollection RetrieveMultiple(Microsoft.Xrm.Sdk.Query.QueryBase query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultiple", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultipleResponse")]
        System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.EntityCollection> RetrieveMultipleAsync(Microsoft.Xrm.Sdk.Query.QueryBase query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrganizationServiceChannel : HCMApp.HCMSdk.IOrganizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrganizationServiceClient : System.ServiceModel.ClientBase<HCMApp.HCMSdk.IOrganizationService>, HCMApp.HCMSdk.IOrganizationService {
        
        public OrganizationServiceClient() {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Create(Microsoft.Xrm.Sdk.Entity entity) {
            return base.Channel.Create(entity);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateAsync(Microsoft.Xrm.Sdk.Entity entity) {
            return base.Channel.CreateAsync(entity);
        }
        
        public Microsoft.Xrm.Sdk.Entity Retrieve(string entityName, System.Guid id, Microsoft.Xrm.Sdk.Query.ColumnSet columnSet) {
            return base.Channel.Retrieve(entityName, id, columnSet);
        }
        
        public System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.Entity> RetrieveAsync(string entityName, System.Guid id, Microsoft.Xrm.Sdk.Query.ColumnSet columnSet) {
            return base.Channel.RetrieveAsync(entityName, id, columnSet);
        }
        
        public void Update(Microsoft.Xrm.Sdk.Entity entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Microsoft.Xrm.Sdk.Entity entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string entityName, System.Guid id) {
            base.Channel.Delete(entityName, id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string entityName, System.Guid id) {
            return base.Channel.DeleteAsync(entityName, id);
        }
        
        public Microsoft.Xrm.Sdk.OrganizationResponse Execute(Microsoft.Xrm.Sdk.OrganizationRequest request) {
            return base.Channel.Execute(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.OrganizationResponse> ExecuteAsync(Microsoft.Xrm.Sdk.OrganizationRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public void Associate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, HCMApp.HCMSdk.EntityReferenceCollection relatedEntities) {
            base.Channel.Associate(entityName, entityId, relationship, relatedEntities);
        }
        
        public System.Threading.Tasks.Task AssociateAsync(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, HCMApp.HCMSdk.EntityReferenceCollection relatedEntities) {
            return base.Channel.AssociateAsync(entityName, entityId, relationship, relatedEntities);
        }
        
        public void Disassociate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, HCMApp.HCMSdk.EntityReferenceCollection relatedEntities) {
            base.Channel.Disassociate(entityName, entityId, relationship, relatedEntities);
        }
        
        public System.Threading.Tasks.Task DisassociateAsync(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, HCMApp.HCMSdk.EntityReferenceCollection relatedEntities) {
            return base.Channel.DisassociateAsync(entityName, entityId, relationship, relatedEntities);
        }
        
        public Microsoft.Xrm.Sdk.EntityCollection RetrieveMultiple(Microsoft.Xrm.Sdk.Query.QueryBase query) {
            return base.Channel.RetrieveMultiple(query);
        }
        
        public System.Threading.Tasks.Task<Microsoft.Xrm.Sdk.EntityCollection> RetrieveMultipleAsync(Microsoft.Xrm.Sdk.Query.QueryBase query) {
            return base.Channel.RetrieveMultipleAsync(query);
        }
    }
}
