//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\r.bozorgi\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"http://crm2016.sdp.com/Test" /generateActions /out:"C:\Users\r.bozorgi\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\Actions.cs" /namespace:"CrmEarlyBound" /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"r.bozorgi" /password:"**********" /domain:"sdp.com" 
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_ActionTest")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class new_ActionTestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool EscalatedBy
		{
			get
			{
				if (this.Parameters.Contains("EscalatedBy"))
				{
					return ((bool)(this.Parameters["EscalatedBy"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["EscalatedBy"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_ActionTestRequest()
		{
			this.RequestName = "new_ActionTest";
			this.EscalatedBy = default(bool);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("new_ActionTest")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class new_ActionTestResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public new_ActionTestResponse()
		{
		}
		
		public bool Priority
		{
			get
			{
				if (this.Results.Contains("Priority"))
				{
					return ((bool)(this.Results["Priority"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_accountleadactiontst")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class new_accountleadactiontstRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string jobtitle
		{
			get
			{
				if (this.Parameters.Contains("jobtitle"))
				{
					return ((string)(this.Parameters["jobtitle"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["jobtitle"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_accountleadactiontstRequest()
		{
			this.RequestName = "new_accountleadactiontst";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("new_accountleadactiontst")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class new_accountleadactiontstResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public new_accountleadactiontstResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("new_tstclassaction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class new_tstclassactionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string information
		{
			get
			{
				if (this.Parameters.Contains("information"))
				{
					return ((string)(this.Parameters["information"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["information"] = value;
			}
		}
		
		public bool NewArgument
		{
			get
			{
				if (this.Parameters.Contains("NewArgument"))
				{
					return ((bool)(this.Parameters["NewArgument"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["NewArgument"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public new_tstclassactionRequest()
		{
			this.RequestName = "new_tstclassaction";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("new_tstclassaction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class new_tstclassactionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public new_tstclassactionResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/dev1/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("dev1_p1")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class dev1_p1Request : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool pp
		{
			get
			{
				if (this.Parameters.Contains("pp"))
				{
					return ((bool)(this.Parameters["pp"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["pp"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public dev1_p1Request()
		{
			this.RequestName = "dev1_p1";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/dev1/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("dev1_p1")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class dev1_p1Response : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public dev1_p1Response()
		{
		}
	}
}
